### ISSUE TITLE
Allow the CSS property editor to have a CSS selector

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#2168]
The CSS property editor should have, as an option, a CSS selector proceeding it.

This will bring it closer to how most browsers use their CSS dev tools and would allow for more meaningful interactions, such as stacking various selectors together that relate to a particular element.

An example:
```css
.my-component {
    background: "red"
}

.my-component.my-component__modifier {
    background: "green"
}
```

The CSS property editor in this situation would be rendered twice, with two different selectors. This will also enable future tasks for:

- Showing overrides from more precise selectors
- Adding/Removing CSS for pseudo selectors
