### ISSUE TITLE
Css font changes do not change fast-button

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#3578]
**Describe the bug; what happened?**
Using an instance of `fast-button` web component and assigning a class or element style css changes to `font-size`, `font-weight` and `font` have no effect. Because the `<button/>` element in the shadow DOM default styling is still being set.

```CSS
fast-button {
   font-size: 30px;
   font-weight: bold;
}
```

```HTML
<fast-button>Button</fast-button>
```

```CSS
.button {
   font-size: 30px;
   font-weight: bold;
}
```

```HTML
<fast-button class="button">Button</fast-button>
```

![image](https://user-images.githubusercontent.com/37851214/88710919-3045ad80-d0cc-11ea-8513-b6c11a346c09.png)
