### ISSUE TITLE
Height is not being respected in fast-slider

### ISSUE THREAD

**Issue by barahonajm** [microsoft/fast#3644]
**Describe the bug; what happened?**

When you set the height to 0% of `<fast-slider orientation="vertical">`  it is not being respected since it already has a min-height set to:

```css
    :host(.vertical) {
        height: 100%;
        min-height: calc(var(--design-unit) * 60px);
        min-width: calc(var(--design-unit) * 20px);
    }
```

**What are the steps to reproduce the issue?**

Example:
Run the following code:

```html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="UTF-8" />
    <script type="module" src="https://unpkg.com/@fluentui/web-components"></script>
  </head>

  <body>

      <fluent-design-system-provider use-defaults>
          <fluent-slider max="100" value="20" style="height: 0%;"  orientation="vertical"></fluent-slider>  
      </fluent-design-system-provider>
    
  </body>

</html>
```

**What behavior did you expect?**

I would like the height to be adjusted at least at a minimum size of the thumb

**Is there any additional context?**

This issue is related to #3634, which has already been fixed, but for the height the solution will not be too straightforward at least from my point of view

From what I saw I believe the fix here will not be as simple as setting it to `thumb-size * 1px` because doing that the slider will normally appear with a height of `16px`. The normal `<input type="range">` will appear as 160px height when you did not set the value manually and the `min-height` remains as auto
