### ISSUE TITLE
Inconsistencies between fast-text-field and fast-text-area

### ISSUE THREAD

**Issue by ben-girardet** [microsoft/fast#3688]
**Describe the bug; what happened?**

When using `<fast-text-field>` and `<fast-text-area>` with a `width: 100%;` they do not act in a consistent way.

* fast-text-field grow to 100% but not its control do not fit its entire width
* fast-text-area do not grow to 100% but its control fits its entire width

**What are the steps to reproduce the issue?**

```html
<div class="container">
  <fast-text-field>
    Fast text field
  </fast-text-field>
  <fast-text-area>
    Fast text area
  </fast-text-area>
</div>
```

```css
.container {
  width: 600px;
  margin: auto;
  padding: 40px 0;
}

.container fast-text-field,
.container fast-text-area {
  width: 100%;
  border: dotted 2px #fcc;
}

.container fast-text-field::part(control),
.container fast-text-area::part(control) {
  background-color: #ccc; /* in order to reveal the control width bug */
} 
```

**What behavior did you expect?**

The text area should take the whole width and the control inside each field must take the whole width of the field itself

**If applicable, provide screenshots:**

<img width="621" alt="Capture d’écran 2020-08-11 à 21 23 10" src="https://user-images.githubusercontent.com/4275071/89939945-10100580-dc19-11ea-87ff-67b87bb5b2bc.png">

**In what environment did you see the issue?**

* MacOS
* Chrome

**Comment by ben-girardet** [comment]
Probably related, when using a slotted content in the `start` slot it pushes the control away to the right.

```html
<div class="container">
  <fast-text-field>
    <span slot="start"></span> <!-- faking some start slot content -->
    Fast text field
  </fast-text-field>
</div>
```

```css
.container {
  width: 600px;
  margin: auto;
  padding: 40px 0;
}

.container fast-text-field {
  width: 100%;
  border: dotted 2px #fcc;
}

.container fast-text-field::part(control) {
  background-color: #ccc; /* in order to reveal the control width bug */
} 

.container fast-text-field::part(start) {
  width: 24px;
  height: 24px;
  background: red;
  border-radius: 4px;
}
```

Here is a screenshot of this bug:

<img width="631" alt="Capture d’écran 2020-08-11 à 21 26 57" src="https://user-images.githubusercontent.com/4275071/89940181-68470780-dc19-11ea-8e9d-a97e9455ae1a.png">
