### ISSUE TITLE
Replace instances of the deprecated React component Label with the native label element

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4262]
# Description

Replace the `<Label />` component from the deprecated package `@microsoft/fast-components-react-msft` in `./sites/site-utilities/src/components/accent-color-picker-index.tsx` with a native `<label>` element that has styling tied to the `<fast-design-system-provider>`.

Add to the styles:
```css
label {
    font-size: var(--type-ramp-base-font-size);
    line-height: var(--type-ramp-base-line-height);
    color: var(--neutral-foreground-rest);
}
```
