### ISSUE TITLE
Re-add Code QL Security Scanner

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#4405]
**Describe the bug; what happened?**
`ci-weekly.yml` previously included a code section for code quality analysis.  This seems to have been removed and requires adding back in.

**What are the steps to reproduce the issue?**
The code that should be re-added includes:
```
  code_scan:
    name: Validate Security

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: javascript

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
```
**What behavior did you expect?**
This code should be added to the weekly yml file

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Is there any additional context?**
