### ISSUE TITLE
Could/Should ergonomic layout solutions be facilitated by the component package

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4694]
# Abstract

There is currently no shortcut for laying out common patterns on a page. A user would have to create their own styles in order to, for example, create a grid of `<fast-card>` components. Even if they did create a containing element that implemented `flexbox`, as an example, they would still need to add `margin` to each of the `<fast-card>` components.

Should there be some way to facilitate users laying out components in a grid?

### Web component

A layout/grid web component that would write the styles, resulting in something like:

```css
:host {
    display: flex;
    flex-wrap: wrap;
}

:host > * {
    margin: 0 16px 16px 0; // giving the direct children of the layout/grid component margin on right and bottom for spacing
}
```

### Helper classes

Is there a way to do this with helper classes to avoid the need for a new web component? I'm aware of the effort that is currently ongoing to add helper classes for headings.

## Discussion

This is an open discussion, requesting feedback on solutions for this issue.
