### ISSUE TITLE
fix: dangerousHTML in fast-element is not exported

### ISSUE THREAD

**Issue by tebinraouf** [microsoft/fast#6661]
# 🐛 Bug Report

I'm currently using the following versions of `fast-element` and `fast-foundation`, which has the `dangerousHTML` directive. 
```
    "@microsoft/fast-element": "2.0.0-beta.18",
    "@microsoft/fast-foundation": "3.0.0-alpha.22",
```

`dangerousHTML` was removed and replaced by https://github.com/microsoft/fast/pull/6577 which was released in ` "@microsoft/fast-element": "2.0.0-beta.20"` as noted in the [changelog](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-element/CHANGELOG.md#200-beta20)

Even though `dangerousHTML` was replaced by `html.partial` in `v2.0.0-beta.20`, it is affecting `"@microsoft/fast-element": "2.0.0-beta.18",`

Due to this, I'm getting this error: 

```sh
ModuleDependencyError: export 'dangerousHTML' (imported as 'dangerousHTML') was not found in '@microsoft/fast-element' (possible exports: ArrayObserver, AttributeConfiguration, AttributeDefinition, Binding, CSSDirective, ChildrenDirective, Compiler, DOM, DOMAspect, ElementController, ElementStyles, ExecutionContext, FAST, FASTElement, FASTElementDefinition, HTMLBindingDirective, HTMLDirective, HTMLView, InlineTemplateDirective, Markup, NodeObservationDirective, Observable, Parser, PropertyChangeNotifier, RefDirective, RepeatBehavior, RepeatDirective, SlottedDirective, SourceLifetime, Splice, SpliceStrategy, SpliceStrategySupport, StatelessAttachedAttributeDirective, SubscriberSet, Updates, ViewTemplate, attr, bind, booleanConverter, children, createMetadataLocator, createTypeRegistry, css, cssDirective, customElement, elements, emptyArray, html, htmlDirective, lengthOf, listener, normalizeBinding, nullableBooleanConverter, nullableNumberConverter, observable, oneTime, ref, repeat, slotted, volatile, when)
....
````

Here is this code excerpt from `yarn.lock` file: 
```
"@microsoft/fast-element@npm:2.0.0-beta.18":
  version: 2.0.0-beta.18
  resolution: "@microsoft/fast-element@npm:2.0.0-beta.18"
  checksum: 855c492f0cf506ad998979f4e2277f01ca7606c4650f5d638e63ffd3248147403bfd83cfdc6faf692a1c2e96d8ad00a82f3997abccd3a23ea9604a60b4ee4983
  languageName: node
  linkType: hard

"@microsoft/fast-element@npm:^2.0.0-beta.18, @microsoft/fast-element@npm:^2.0.0-beta.6":
  version: 2.0.0-beta.21
  resolution: "@microsoft/fast-element@npm:2.0.0-beta.21"
  checksum: 982a0c22c1395b7865420a9f20f7bbfb7c2248ae04ad5b5df224050fc206072c38ac5c8cdbf964f0d274f172989b56d2a6b346a3a0339d7eb125452848298c81
  languageName: node
  linkType: hard

"@microsoft/fast-foundation@npm:3.0.0-alpha.22":
  version: 3.0.0-alpha.22
  resolution: "@microsoft/fast-foundation@npm:3.0.0-alpha.22"
  dependencies:
    "@floating-ui/dom": ^1.0.3
    "@microsoft/fast-element": ^2.0.0-beta.18
    "@microsoft/fast-web-utilities": ^6.0.0
    tabbable: ^5.2.0
    tslib: ^2.4.0
  checksum: e696f1f78a92d5dcb4c0bb2f2657bc6d111c903b78790e6e6f314c50f02b0968c5597cb088a978cbeda2e2b9e9777300588c558388f9df651e06440c6c6d150f
  languageName: node
  linkType: hard
```

## 🤔 Expected Behavior

`dangerousHTML` should be available `2.0.0-beta.18` even though it was replaced in version `2.0.0-beta.20`. 

## 😯 Current Behavior

```sh
ModuleDependencyError: export 'dangerousHTML' (imported as 'dangerousHTML') was not found in '@microsoft/fast-element' (possible exports: ArrayObserver, AttributeConfiguration, AttributeDefinition, Binding, CSSDirective, ChildrenDirective, Compiler, DOM, DOMAspect, ElementController, ElementStyles, ExecutionContext, FAST, FASTElement, FASTElementDefinition, HTMLBindingDirective, HTMLDirective, HTMLView, InlineTemplateDirective, Markup, NodeObservationDirective, Observable, Parser, PropertyChangeNotifier, RefDirective, RepeatBehavior, RepeatDirective, SlottedDirective, SourceLifetime, Splice, SpliceStrategy, SpliceStrategySupport, StatelessAttachedAttributeDirective, SubscriberSet, Updates, ViewTemplate, attr, bind, booleanConverter, children, createMetadataLocator, createTypeRegistry, css, cssDirective, customElement, elements, emptyArray, html, htmlDirective, lengthOf, listener, normalizeBinding, nullableBooleanConverter, nullableNumberConverter, observable, oneTime, ref, repeat, slotted, volatile, when)
....
````

`node_modules` under `fast-foundation v3.0.0-alpha.22` has `fast-element v2.0.0-beta.21`. As a result, I see the following errors too:
<img width="886" alt="image" src="https://user-images.githubusercontent.com/23642967/223313686-6f81ba68-3d58-4448-b820-a873b7e65cd8.png">

## 💁 Possible Solution

It might be because `fast-foundation` depends on the latest `fast-elemenet` here https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/package.json#L99. 

I would change the dependency to fixed. 
From: ` "@microsoft/fast-element": "^2.0.0-beta.21",`
To:  "@microsoft/fast-element": "2.0.0-beta.21",

While this does not fix the previous version issues. I'm looking for possible solutions. 

## 🔦 Context

This error happens currently when using `yarn v3.4.1`. 
This works on `npm v8.5.0` 
This works with pnpm v6.16.1`

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]
